
[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
anyhow = { version = "1.0.92" }
serde = { version = "1.0.214" }
serde_json = { version = "1.0.132" }
oxc_allocator = { version = "0.35.0" }
oxc_ast = { version = "0.35.0", features = ["serialize"] }
oxc_parser = { version = "0.35.0" }
oxc_span = { version = "0.35.0" }
oxc_syntax = { version = "0.35.0" }
oxc_diagnostics = { version = "0.35.0" }
thiserror = { version = "2.0.1" }
htmlize = { version = "1.0.5" }
